import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {OpenRooms} from "../components/OpenRooms";
import {Grid, GridItem, Heading} from "@chakra-ui/react";
import {Header} from "../components/Header";
import {MyRooms} from "../components/MyRooms";
import { useAccount } from 'wagmi';
import {CreateRooms} from "../components/CreateRooms";

const Home: () => (string | JSX.Element) = () => {

  const { address, isConnected } = useAccount()

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock Paper Scissor Web3 Game</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Grid
          gap='1'
          fontWeight='bold'
          templateAreas={`"header header"
                  "nav main"
                  "nav footer"`}
        >
          <GridItem pl='2' area={'header'}>
            <Header/>
          </GridItem>
          <GridItem pl='2' area={'nav'}>
            <Heading as='h2' size='xl'>
              Open Rooms <CreateRooms/>
            </Heading>
            <OpenRooms />
          </GridItem>
          <GridItem pl='2' area={'main'}>
            <Heading as='h2' size='xl'>
              My Rooms
            </Heading>
            {isConnected && (<MyRooms address={address} />)}
          </GridItem>
          <GridItem pl='2' area={'footer'}>
            <Heading as='h2' size='xl'>
              Game
            </Heading>
          </GridItem>
        </Grid>
      </main>


    </div>
  );
};


export default Home;
